package by.eventcat.custom.exceptions;

/**
 * Error codes enum
 */
public enum CustomErrorCodes {
    NO_CALLING_DATA_FOUND,
    INCORRECT_INDEX,
    INCORRECT_INPUT_DATA,
    INCORRECT_DATE_FORMAT,
    INCORRECT_DATE,
    INCORRECT_REQUEST_PARAMETERS,
    NO_ACTIONS_MADE,
    ACTIONS_ERROR,
    NO_DUPLICATE_DATA_PERMITTED,
    INPUT_INDEX_OF_NON_EXISTING_EVENT,
    INPUT_INDEX_OF_NON_EXISTING_CATEGORY
}
